crm/urls.py
from django.urls import path
from . import views
# from crm.views import apartments

urlpatterns = [
    path('',views.DashboardView,name='dashboard'),

    path('settings/',views.SettingsListView.as_view(),name='setting_list'),
    path('settings/<int:pk>/edit', views.SettingsUpdateView.as_view(), name='setting_edit'),
    path('settings/new/', views.SettingsCreateView.as_view(), name='setting_new'),

    path('apartment/',views.ApartmentListView.as_view(),name='apartment_list'),
    path('apartment/<int:pk>/edit', views.ApartmentUpdateView.as_view(), name='apartment_edit'),
    path('apartment/new/', views.ApartmentCreateView.as_view(), name='apartment_new'),
    path('apartment/<int:pk>/delete', views.ApartmentDeleteView.as_view(), name='apartment_delete'),

    path('landlord/',views.LandlordListView.as_view(),name='landlord_list'),
    path('landlord/<int:pk>/edit', views.LandlordUpdateView.as_view(), name='landlord_edit'),
    path('landlord/new/', views.LandlordCreateView.as_view(), name='landlord_new'),
    path('landlord/<int:pk>/delete', views.LandlordDeleteView.as_view(), name='landlord_delete'),
    path('landlord/<int:pk>/sample', views.SampleStatementView.as_view(), name='landlord_sample_statement'),

    path('tenant/',views.TenantListView.as_view(),name='tenant_list'),
    path('tenant/<int:pk>/edit', views.TenantUpdateView.as_view(), name='tenant_edit'),
    path('tenant/new/', views.TenantCreateView.as_view(), name='tenant_new'),
    path('tenant/<str:pk>/edit/bank-account', views.BankAccountUpdateView.as_view(), name='bank_account_update'),
    path('tenant/<str:pk>/edit/credit-card', views.CreditCardUpdateView.as_view(), name='credit_card_update'),
    path('tenant/<int:pk>/delete', views.TenantDeleteView.as_view(), name='tenant_delete'),
    path('tenant/upload', views.tenant_upload, name='tenant_upload'),

    path('booking/',views.BookingListView.as_view(),name='booking_list'),
    path('booking/<int:pk>/edit', views.BookingUpdateView.as_view(), name='booking_edit'),
    path('booking/new/', views.BookingCreateView.as_view(), name='booking_new'),


    path('batch/',views.BatchListView.as_view(),name='batch_list'),
    # path('batch/new/', views.create_batch, name='batch_new'),
    path('batch/new/', views.create_batch, name='batch_new_1'),
    path('batch/<int:pk>/review/', views.BatchDetailsView.as_view(), name='batch_review'),
    path('batch/<int:pk>/send/', views.send_batch, name='batch_send'),
    path('batch/<int:pk>/delete', views.BatchDeleteView.as_view(), name='batch_delete'),

    path('payment/<int:pk>/edit/', views.PaymentUpdateView.as_view(), name='payment_update'),




 ]

send/urls.py
from django.urls import path
from send import views

app_name = 'send'

urlpatterns = [
    path('statement/<int:pk>',views.statement, name='statement'),
    path('reminder/<int:pk>',views.reminder, name='reminder'),
]

third_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views
from django.urls import reverse_lazy

from django.contrib.auth import views as auth_views ### Custom LoginView
from crm.forms import LoginForm ### Custom LoginView


urlpatterns = [
    path('',include('crm.urls')),
    path('send/',include('send.urls')),
    path('admin/', admin.site.urls, name="admin"),
    # path('accounts/login/', views.LoginView.as_view(template_name='registration/login.html'), name='login'), #Built-in LoginView
    path('login/', auth_views.login, name='login', kwargs={"authentication_form":LoginForm}),  ### Custom LoginView
    path('logout/', views.LogoutView.as_view(next_page=reverse_lazy('dashboard')), name='logout'),

    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')), # <--
]

crm/views.py
from django.shortcuts import render, redirect
from django.views.generic import View,TemplateView,ListView,DetailView,UpdateView,CreateView,DeleteView
from .models import Apartment,Landlord,Tenant,Booking,Settings,Profile,Batch,Payment
from django.urls import reverse_lazy, reverse
from .forms import ApartmentForm,LandlordForm,TenantForm,BookingForm,SettingsForm, CreditCardForm, BankAccountForm, BatchForm, PaymentForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
import time
import re, string

from django_tables2 import RequestConfig
from .tables import ApartmentTable
# Create your views here.

#CSV UPLOAD IMPORTS
import csv # Used to import CSV
import io # Used for working with io streams (streams of data)
from django.contrib import messages #To display a message prompt
from third_project.utils import create_context, str_to_bool, has_empty_fields

from bambora.config import settings
from bambora.profile import get_profile, delete_profile, update_or_create_profile, delete_card, update_card, create_card, create_profile, update_profile
from bambora.batch import create_eft_batch
from bambora.batch_report import get_batch

@login_required
def DashboardView(request):
    count_apartment = Apartment.objects.all().count()
    count_landlord = Landlord.objects.all().count()
    count_tenant= Tenant.objects.all().count()
    count_booking= Booking.objects.all().count()
    context = {'count_apartment':count_apartment,'count_landlord':count_landlord, 'count_tenant':count_tenant, 'count_booking':count_booking }
    return render(request,'crm/dashboard.html', context)

# SETTINGS
class SettingsListView(LoginRequiredMixin,ListView):
    login_url = '/accounts/login/'
    context_object_name = 'settings'
    model = Settings

class SettingsUpdateView(LoginRequiredMixin,UpdateView):
    login_url = '/accounts/login/'
    form_class = SettingsForm
    model = Settings

class SettingsCreateView(LoginRequiredMixin,CreateView):
    login_url = '/accounts/login/'
    form_class = SettingsForm
    model = Settings


# APARTMENT

class ApartmentListView(LoginRequiredMixin,ListView):
    login_url = '/accounts/login/'
    context_object_name = 'apartments'
    model = Apartment

    #ENTRY COUNT: get_context_data allows us to inject extra content into class-based views. Here we want to inject number of records, which is not in the model, but calculated
    def get_context_data(self,**kwargs):
        context = super(ApartmentListView,self).get_context_data(**kwargs)
        context['count_apartment'] = Apartment.objects.all().count()
        return context

class ApartmentUpdateView (LoginRequiredMixin,UpdateView):
    login_url = '/accounts/login/'
    form_class = ApartmentForm
    model = Apartment

class ApartmentCreateView(LoginRequiredMixin,CreateView):
    login_url = '/accounts/login/'
    form_class = ApartmentForm
    model = Apartment

class ApartmentDeleteView(LoginRequiredMixin,DeleteView):
    login_url = '/accounts/login/'
    model = Apartment
    success_url = reverse_lazy('apartment_list')


# LANDLORD

class LandlordListView(LoginRequiredMixin,ListView):
    login_url = '/accounts/login/'
    context_object_name = 'landlords'
    model = Landlord

    def get_context_data(self,**kwargs):
        context = super(LandlordListView,self).get_context_data(**kwargs)
        context['count_landlord'] = Landlord.objects.all().count()
        return context

class LandlordUpdateView (LoginRequiredMixin,UpdateView):
    login_url = '/accounts/login/'
    form_class = LandlordForm
    model = Landlord

class LandlordCreateView(LoginRequiredMixin,CreateView):
    login_url = '/accounts/login/'
    form_class = LandlordForm
    model = Landlord

class LandlordDeleteView(LoginRequiredMixin,DeleteView):
    login_url = '/accounts/login/'
    model = Landlord
    success_url = reverse_lazy('landlord_list')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = self.get_success_url()
        fail_url = 'landlord_delete'
        existing_profiles = self.object.profile_set.all()
        # import pdb; pdb.set_trace()

        ### Delete both on local and Bambora ###
        if existing_profiles:
            for profile in existing_profiles:
                payload = {
                    'profiles_api_key': settings["profiles_api_key"],
                    'sub_merchant_id': profile.landlord.sub_merchant_id,
                    'customer_code': profile.customer_code,
                }

                response = delete_profile(payload)

                if response.status_code != 200:
                    message = "Error: {}".format(response.json())
                    messages.info(self.request, message)
                    return redirect(fail_url, pk=self.object.id)

            self.object.delete()
            return HttpResponseRedirect(success_url)

        ### Delete on local only (does not exist on Bambora)###
        else:
            self.object.delete()
            return HttpResponseRedirect(success_url)

class SampleStatementView(TemplateView):
    template_name = "sample_statement.html"
    
    def get_context_data(self,**kwargs):
        context = super(SampleStatementView,self).get_context_data(**kwargs)
        context = create_context(self.kwargs['pk'])
        return context


# TENANT

class TenantListView(LoginRequiredMixin,ListView):
    login_url = '/accounts/login/'
    context_object_name = 'tenants'
    model = Tenant

    def get_context_data(self,**kwargs):
        context = super(TenantListView,self).get_context_data(**kwargs)
        context['count_tenant'] = Tenant.objects.all().count()
        return context

@login_required
def tenant_upload(request):
    if request.method == "GET": #Pulling the tenant_upload page and form when someone calls the function view
        return render(request,"tenant_upload.html")

    csv_file = request.FILES['file'] #We grab the file from the form using the 'file' name tag (in template)
    if not csv_file.name.endswith('.csv'): #We check if the file is .csv exention, and  display prompt message if not
        messages.error(request,'This is not a CSV file')

    data_set = csv_file.read().decode('UTF-8') #This is from the csv import. Allows us to read the csv file.
    io_string = io.StringIO(data_set) #Returns a stream of strings for reading or writing
    next(io_string) #Skips the first line of the io_string file
    for column in csv.reader(io_string, delimiter=',',quotechar='|'):
        _, created = Tenant.objects.update_or_create(
            name=column[0],
            last_name=column[1],
            email=column[2],
            phone=column[3]
        )
    context={}
    return render(request, "tenant_confirm_upload.html", context)

class TenantUpdateView (LoginRequiredMixin,UpdateView):
    login_url = '/accounts/login/'
    form_class = TenantForm
    model = Tenant

    def form_valid(self, form):
        # import pdb; pdb.set_trace()
        self.object = form.save(commit=False)
        fail_url = 'tenant_edit'
        success_url = 'tenant_list'
        existing_profiles = Profile.objects.filter(tenant=self.object)

        ### Update both on local and Bambora ###
        if existing_profiles:
            for profile in existing_profiles:
                data = { 
                    "billing": {
                        "name": self.object.full_name, 
                        "phone_number": self.object.phone,
                        "email_address": self.object.email,
                    }
                }

                payload = {
                    'profiles_api_key': settings["profiles_api_key"],
                    'sub_merchant_id': profile.landlord.sub_merchant_id,
                    'customer_code': profile.customer_code,
                    'data': data
                }
                
                response = update_profile(payload)

                if response.status_code != 200:
                    message = "Error: {}".format(response.json())
                    messages.info(self.request, message)
                    return redirect(fail_url, pk=self.object.id)

            self.object = form.save()
            return super().form_valid(form)
        else:
            ### Update local only (does not exist on Bambora)###
            self.object = form.save()
            return super().form_valid(form)

class TenantCreateView(LoginRequiredMixin,CreateView):
    login_url = '/accounts/login/'
    form_class = TenantForm
    model = Tenant
    template_name = "tenant_form.html"
    success_url = reverse_lazy('tenant_list')

class TenantDeleteView(LoginRequiredMixin,DeleteView):
    login_url = '/accounts/login/'
    model = Tenant
    success_url = reverse_lazy('tenant_list')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = self.get_success_url()
        fail_url = 'tenant_delete'
        existing_profiles = Profile.objects.filter(tenant=self.object)
        # import pdb; pdb.set_trace()

        ### Delete both on local and Bambora ###
        if existing_profiles:
            for profile in existing_profiles:
                payload = {
                    'profiles_api_key': settings["profiles_api_key"],
                    'sub_merchant_id': profile.landlord.sub_merchant_id,
                    'customer_code': profile.customer_code,
                }

                response = delete_profile(payload)

                if response.status_code != 200:
                    message = "Error: {}".format(response.json())
                    messages.info(self.request, message)
                    return redirect(fail_url, pk=self.object.id)

            self.object.delete()
            return HttpResponseRedirect(success_url)

        ### Delete on ocal only (does not exist on Bambora)###

crm/templates/crm/apartment_form.html
{% extends 'crm/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
  <h1>
    {% if not form.instance.pk %}
    New Apartment
    {% else %}
    Update Apartment
    {% endif %}
  </h1>
  <hr />
  <form class="" method="POST">
    {% csrf_token %}
    <div class="col-4">{{form.nickname|as_crispy_field}}</div>
    <div class="col-4">{{form.address|as_crispy_field}}</div>
    <div class="col-4">{{form.unit|as_crispy_field}}</div>
    <div class="col-4">{{form.landlord|as_crispy_field}}</div>

    <button type="submit" class="btn btn-primary btn-lg">Save</button>
    <a class="btn btn-secondary btn-lg" href="{% url 'apartment_list' %}">Cancel</a>
  </form>

{% endblock %}

crm/templates/crm/apartment_list.html
{% extends 'crm/base.html' %}
{% load staticfiles %}

{% block content %}
<table>
  <td></td>
</table>


  <!-- Breadcrumbs-->
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <a href="{% url 'dashboard' %}">Dashboard</a>
    </li>
    <li class="breadcrumb-item active">Databases</li>
  </ol>

<div class="container">

</div>
  <!-- DataTables Example -->
  <div class="card mb-3">
    <div class="card-header">
      <i class="fas fa-building"></i>
      <a class = 'btn btn-primary pull-right' href="{% url 'apartment_new' %}">+New apartment</a>
      Properties</div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
          <thead>
            <tr>

              <th>#</th>
              <th>Nickname</th>
              <th>Address</th>
              <th>Unit</th>
              <th>Landlord</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tfoot>
            <tr>
              <th>#</th>
              <th>Nickname</th>
              <th>Address</th>
              <th>Unit</th>
              <th>Landlord</th>
              <th>Actions</th>
            </tr>
          </tfoot>
          <tbody>
          {% for apartment in apartments %}
            <tr>
              <td>{{apartment.pk}}</td>
              <td>{{apartment.nickname}}</td>
              <td>{{apartment.address}}</td>
              <td>{{apartment.unit}}</td>
              <td>{{apartment.landlord}}</td>
              <td><a href="{% url 'apartment_edit' pk=apartment.pk %}"><span class="fa fa-pencil"></span></a>
                   <a href="{% url 'apartment_delete' pk=apartment.pk %}"><span class="fa fa-remove"></span></a></td>
            </tr>
          {% endfor %}
          </tbody>

        </table>
      </div>
    </div>
    <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
  </div>
  </div>

{% endblock %}

crm/templates/crm/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>SB Admin - Blank Page</title>

  <!-- Custom fonts for this template-->
  <link href="{% static 'startbootstrap/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">


  <!-- Page level plugin CSS-->
  <link href="{% static 'startbootstrap/vendor/datatables/dataTables.bootstrap4.css' %}" rel="stylesheet">


  <!-- Custom styles for this template-->
  <link href="{% static 'startbootstrap/css/sb-admin.css' %}" rel="stylesheet">


<!-- ##### -->

<link rel="stylesheet" href="node_modules/octicons/build/font/octicons.css">

<!-- CSS -->
<link rel="stylesheet" href="{% static 'css/crm.css' %}">

<!-- JS -->
<script src="{% static 'js/crm.js' %}"></script>

<!-- BOOSTRAP -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<!-- Alternative to Bootstrap 3 Glyphicons -->
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">


<!-- Datetimepicker -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/gijgo/1.9.13/combined/js/gijgo.min.js "></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/gijgo/1.9.13/combined/css/gijgo.min.css" />



</head>

<body id="page-top">

  <nav class="navbar navbar-expand navbar-dark bg-dark static-top">

    <a class="navbar-brand mr-1" href="index.html">Koumba</a>

    <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
      <i class="fas fa-bars"></i>
    </button>

    <!-- Navbar Search -->
    <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
      <!-- <div class="input-group">
        <input type="text" class="form-control" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
        <div class="input-group-append">
          <button class="btn btn-primary" type="button">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </div> -->
    </form>

    <!-- Navbar -->
    <span style='color:white;'>Welcome {{user.username}}!</span>
    <ul class="navbar-nav ml-auto ml-md-0">
      <li class="nav-item dropdown no-arrow mx-1">
        <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-bell fa-fw"></i>
          <span class="badge badge-danger"></span>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="alertsDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item dropdown no-arrow mx-1">
        <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-envelope fa-fw"></i>
          <span class="badge badge-danger"></span>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="messagesDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item dropdown no-arrow">
        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-user-circle fa-fw"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
          <a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a>
          <a class="dropdown-item" href="{% url 'setting_list' %}">Settings</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">Logout</a>
        </div>
      </li>
    </ul>

  </nav>

  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="sidebar navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'dashboard' %}">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Dashboard</span>
        </a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="pagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-fw fa-table"></i>
          <span>Databases</span>
        </a>
        <div class="dropdown-menu" aria-labelledby="pagesDropdown">
          <h6 class="dropdown-header">Login Screens:</h6>
          <a class="dropdown-item" href="{% url 'apartment_list' %}">Properties</a>
          <a class="dropdown-item" href="{% url 'landlord_list' %}">Landlords</a>
          <a class="dropdown-item" href="{% url 'tenant_list' %}">Tenants</a>
          <a class="dropdown-item" href="{% url 'booking_list' %}">Bookings</a>
          <a class="dropdown-item" href="{% url 'batch_list' %}">Batches</a>

          <!-- <div class="dropdown-divider"></div>
          <h6 class="dropdown-header">Other Pages:</h6>
          <a class="dropdown-item" href="404.html">404 Page</a>
          <a class="dropdown-item active" href="blank.html">Blank Page</a> -->
        </div>
      <!-- </li>
      <li class="nav-item">
        <a class="nav-link" href="charts.html">
          <i class="fas fa-fw fa-chart-area"></i>
          <span>Charts</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="tables.html">
          <i class="fas fa-fw fa-table"></i>
          <span>Tables</span></a>
      </li> -->
    </ul>

    <div id="content-wrapper">


      <div class="container-fluid">



        <!-- ###Page Content -->
        <!-- <hr>
        <p>This is a great starting point for new custom pages.</p> -->
        {% block content %}
        {% endblock %}
      </div>
      <!-- /.container-fluid -->

      <!-- Sticky Footer -->
      <footer class="sticky-footer">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Copyright © Your Website 2019</span>
          </div>
        </div>
      </footer>

    </div>
    <!-- /.content-wrapper -->

  </div>
  <!-- /#wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="{% url 'logout' %}">Logout</a>
        </div>
      </div>
    </div>
  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'startbootstrap/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'startbootstrap/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'startbootstrap/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'startbootstrap/js/sb-admin.min.js' %}"></script>


  <!-- Page level plugin JavaScript ####TABLES###-->
  <script src="{% static 'startbootstrap/vendor/datatables/jquery.dataTables.js' %}"></script>
  <script src="{% static 'startbootstrap/vendor/datatables/dataTables.bootstrap4.js' %}"></script>

    <!-- Demo scripts for this page ####TABLES###-->
  <script src="{% static 'startbootstrap/js/demo/datatables-demo.js' %}"></script>

</body>

</html>

crm/templates/crm/batch_confirm_delete.html
{% extends 'crm/base.html' %}

{% block content %}

<form method="POST">
  {% csrf_token %}
  <p>Are you sure you want to delete {{object}}?</p>
  <input class="btn btn-danger" type="submit" value="Confirm">
</form>

{% endblock %}

crm/templates/crm/booking_confirm_delete.html
{% extends 'crm/base.html' %}

{% block content %}

{% if messages %}
{% for message in messages %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <strong>Holy guacamole!</strong> {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">×</span>
        </button>
    </div>
{% endfor %}
{% endif %}


<form method="POST">
  {% csrf_token %}
  <p>Are you sure you want to delete {{object}}?</p>
  <input class="btn btn-danger" type="submit" value="Confirm">
</form>

{% endblock %}

crm/templates/crm/booking_list.html
{% extends 'crm/base.html' %}
{% load staticfiles %}

{% block content %}

  <!-- Breadcrumbs-->
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <a href="{% url 'dashboard' %}">Dashboard</a>
    </li>
    <li class="breadcrumb-item active">Databases</li>
  </ol>

  <!-- DataTables Example -->
  <div class="card mb-3">
    <div class="card-header">
      <i class="fas fa-file-signature"></i>
      <a class = 'btn btn-primary pull-right' href="{% url 'booking_new' %}">+New booking</a>
      Bookings</div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
          <thead>
            <tr>
              <th>Status</th>
              <th>Full name</th>
              <th>Check-in</th>
              <th>Check-out</th>
              <th>Landlord</th>
              <th>Apartment</th>
              <th>Rent</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tfoot>
            <tr>
              <th>Status</th>
              <th>Full name</th>
              <th>Check-in</th>
              <th>Check-out</th>
              <th>Landlord</th>
              <th>Apartment</th>
              <th id="tot-rent"></th>
              <th>Actions</th>
            </tr>
          </tfoot>
          <tbody>
          {% for booking in bookings %}
            <tr>
              <td>{{booking.status}}</td>
              <td>{{booking.tenant}}</td>
              <td>{{booking.check_in}}</td>
              <td>{{booking.check_out}}</td>
              <td>{{booking.apartment.landlord}}</td>
              <td>{{booking.apartment}}</td>
              <td>{{booking.rent}}</td>  
              <td>
                <a href="{% url 'send:reminder' pk=booking.pk %}"><span class="fa fa-envelope"></span></a>
                <a href="{% url 'booking_edit' pk=booking.pk %}"><span class="fa fa-pencil"></span></a>
            </tr>
          {% endfor %}
          </tbody>

        </table>
      </div>
    </div>
    <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
  </div>
  </div>

{% endblock %}